package com.qmtec.agent.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class FlumeConfig implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.context_id
     *
     * @mbg.generated
     */
    private Long contextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.monitor_port
     *
     * @mbg.generated
     */
    private Integer monitorPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.startup_time
     *
     * @mbg.generated
     */
    private Date startupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.flume_home
     *
     * @mbg.generated
     */
    private String flumeHome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.process_pid
     *
     * @mbg.generated
     */
    private Integer processPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.profile_name
     *
     * @mbg.generated
     */
    private String profileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.agent_name
     *
     * @mbg.generated
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.server_ip
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.runState
     *
     * @mbg.generated
     */
    private Integer runstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.server_port
     *
     * @mbg.generated
     */
    private String serverPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.file_config_content
     *
     * @mbg.generated
     */
    private String fileConfigContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_config.flume_monitor_content
     *
     * @mbg.generated
     */
    private String flumeMonitorContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.context_id
     *
     * @return the value of t_flume_config.context_id
     *
     * @mbg.generated
     */
    public Long getContextId() {
        return contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.context_id
     *
     * @param contextId the value for t_flume_config.context_id
     *
     * @mbg.generated
     */
    public void setContextId(Long contextId) {
        this.contextId = contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.monitor_port
     *
     * @return the value of t_flume_config.monitor_port
     *
     * @mbg.generated
     */
    public Integer getMonitorPort() {
        return monitorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.monitor_port
     *
     * @param monitorPort the value for t_flume_config.monitor_port
     *
     * @mbg.generated
     */
    public void setMonitorPort(Integer monitorPort) {
        this.monitorPort = monitorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.name
     *
     * @return the value of t_flume_config.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.name
     *
     * @param name the value for t_flume_config.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.code
     *
     * @return the value of t_flume_config.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.code
     *
     * @param code the value for t_flume_config.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.create_time
     *
     * @return the value of t_flume_config.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.create_time
     *
     * @param createTime the value for t_flume_config.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.modify_time
     *
     * @return the value of t_flume_config.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.modify_time
     *
     * @param modifyTime the value for t_flume_config.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.startup_time
     *
     * @return the value of t_flume_config.startup_time
     *
     * @mbg.generated
     */
    public Date getStartupTime() {
        return startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.startup_time
     *
     * @param startupTime the value for t_flume_config.startup_time
     *
     * @mbg.generated
     */
    public void setStartupTime(Date startupTime) {
        this.startupTime = startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.flume_home
     *
     * @return the value of t_flume_config.flume_home
     *
     * @mbg.generated
     */
    public String getFlumeHome() {
        return flumeHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.flume_home
     *
     * @param flumeHome the value for t_flume_config.flume_home
     *
     * @mbg.generated
     */
    public void setFlumeHome(String flumeHome) {
        this.flumeHome = flumeHome == null ? null : flumeHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.process_pid
     *
     * @return the value of t_flume_config.process_pid
     *
     * @mbg.generated
     */
    public Integer getProcessPid() {
        return processPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.process_pid
     *
     * @param processPid the value for t_flume_config.process_pid
     *
     * @mbg.generated
     */
    public void setProcessPid(Integer processPid) {
        this.processPid = processPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.profile_name
     *
     * @return the value of t_flume_config.profile_name
     *
     * @mbg.generated
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.profile_name
     *
     * @param profileName the value for t_flume_config.profile_name
     *
     * @mbg.generated
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName == null ? null : profileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.agent_name
     *
     * @return the value of t_flume_config.agent_name
     *
     * @mbg.generated
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.agent_name
     *
     * @param agentName the value for t_flume_config.agent_name
     *
     * @mbg.generated
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.server_ip
     *
     * @return the value of t_flume_config.server_ip
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.server_ip
     *
     * @param serverIp the value for t_flume_config.server_ip
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.remark
     *
     * @return the value of t_flume_config.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.remark
     *
     * @param remark the value for t_flume_config.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.runState
     *
     * @return the value of t_flume_config.runState
     *
     * @mbg.generated
     */
    public Integer getRunstate() {
        return runstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.runState
     *
     * @param runstate the value for t_flume_config.runState
     *
     * @mbg.generated
     */
    public void setRunstate(Integer runstate) {
        this.runstate = runstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.server_port
     *
     * @return the value of t_flume_config.server_port
     *
     * @mbg.generated
     */
    public String getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.server_port
     *
     * @param serverPort the value for t_flume_config.server_port
     *
     * @mbg.generated
     */
    public void setServerPort(String serverPort) {
        this.serverPort = serverPort == null ? null : serverPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.file_config_content
     *
     * @return the value of t_flume_config.file_config_content
     *
     * @mbg.generated
     */
    public String getFileConfigContent() {
        return fileConfigContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.file_config_content
     *
     * @param fileConfigContent the value for t_flume_config.file_config_content
     *
     * @mbg.generated
     */
    public void setFileConfigContent(String fileConfigContent) {
        this.fileConfigContent = fileConfigContent == null ? null : fileConfigContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_config.flume_monitor_content
     *
     * @return the value of t_flume_config.flume_monitor_content
     *
     * @mbg.generated
     */
    public String getFlumeMonitorContent() {
        return flumeMonitorContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_config.flume_monitor_content
     *
     * @param flumeMonitorContent the value for t_flume_config.flume_monitor_content
     *
     * @mbg.generated
     */
    public void setFlumeMonitorContent(String flumeMonitorContent) {
        this.flumeMonitorContent = flumeMonitorContent == null ? null : flumeMonitorContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", contextId=").append(contextId);
        sb.append(", monitorPort=").append(monitorPort);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", startupTime=").append(startupTime);
        sb.append(", flumeHome=").append(flumeHome);
        sb.append(", processPid=").append(processPid);
        sb.append(", profileName=").append(profileName);
        sb.append(", agentName=").append(agentName);
        sb.append(", serverIp=").append(serverIp);
        sb.append(", remark=").append(remark);
        sb.append(", runstate=").append(runstate);
        sb.append(", serverPort=").append(serverPort);
        sb.append(", fileConfigContent=").append(fileConfigContent);
        sb.append(", flumeMonitorContent=").append(flumeMonitorContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    @Override
    public FlumeConfig clone() throws CloneNotSupportedException {
        return (FlumeConfig) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    public static FlumeConfig.Builder builder() {
        return new FlumeConfig.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private FlumeConfig obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new FlumeConfig();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.context_id
         *
         * @param contextId the value for t_flume_config.context_id
         *
         * @mbg.generated
         */
        public Builder contextId(Long contextId) {
            obj.setContextId(contextId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.monitor_port
         *
         * @param monitorPort the value for t_flume_config.monitor_port
         *
         * @mbg.generated
         */
        public Builder monitorPort(Integer monitorPort) {
            obj.setMonitorPort(monitorPort);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.name
         *
         * @param name the value for t_flume_config.name
         *
         * @mbg.generated
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.code
         *
         * @param code the value for t_flume_config.code
         *
         * @mbg.generated
         */
        public Builder code(String code) {
            obj.setCode(code);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.create_time
         *
         * @param createTime the value for t_flume_config.create_time
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.modify_time
         *
         * @param modifyTime the value for t_flume_config.modify_time
         *
         * @mbg.generated
         */
        public Builder modifyTime(Date modifyTime) {
            obj.setModifyTime(modifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.startup_time
         *
         * @param startupTime the value for t_flume_config.startup_time
         *
         * @mbg.generated
         */
        public Builder startupTime(Date startupTime) {
            obj.setStartupTime(startupTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.flume_home
         *
         * @param flumeHome the value for t_flume_config.flume_home
         *
         * @mbg.generated
         */
        public Builder flumeHome(String flumeHome) {
            obj.setFlumeHome(flumeHome);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.process_pid
         *
         * @param processPid the value for t_flume_config.process_pid
         *
         * @mbg.generated
         */
        public Builder processPid(Integer processPid) {
            obj.setProcessPid(processPid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.profile_name
         *
         * @param profileName the value for t_flume_config.profile_name
         *
         * @mbg.generated
         */
        public Builder profileName(String profileName) {
            obj.setProfileName(profileName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.agent_name
         *
         * @param agentName the value for t_flume_config.agent_name
         *
         * @mbg.generated
         */
        public Builder agentName(String agentName) {
            obj.setAgentName(agentName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.server_ip
         *
         * @param serverIp the value for t_flume_config.server_ip
         *
         * @mbg.generated
         */
        public Builder serverIp(String serverIp) {
            obj.setServerIp(serverIp);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.remark
         *
         * @param remark the value for t_flume_config.remark
         *
         * @mbg.generated
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.runState
         *
         * @param runstate the value for t_flume_config.runState
         *
         * @mbg.generated
         */
        public Builder runstate(Integer runstate) {
            obj.setRunstate(runstate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.server_port
         *
         * @param serverPort the value for t_flume_config.server_port
         *
         * @mbg.generated
         */
        public Builder serverPort(String serverPort) {
            obj.setServerPort(serverPort);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.file_config_content
         *
         * @param fileConfigContent the value for t_flume_config.file_config_content
         *
         * @mbg.generated
         */
        public Builder fileConfigContent(String fileConfigContent) {
            obj.setFileConfigContent(fileConfigContent);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_config.flume_monitor_content
         *
         * @param flumeMonitorContent the value for t_flume_config.flume_monitor_content
         *
         * @mbg.generated
         */
        public Builder flumeMonitorContent(String flumeMonitorContent) {
            obj.setFlumeMonitorContent(flumeMonitorContent);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public FlumeConfig build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    public enum Column {
        contextId("context_id", "contextId", "BIGINT", false),
        monitorPort("monitor_port", "monitorPort", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        code("code", "code", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        startupTime("startup_time", "startupTime", "TIMESTAMP", false),
        flumeHome("flume_home", "flumeHome", "VARCHAR", false),
        processPid("process_pid", "processPid", "INTEGER", false),
        profileName("profile_name", "profileName", "VARCHAR", false),
        agentName("agent_name", "agentName", "VARCHAR", false),
        serverIp("server_ip", "serverIp", "VARCHAR", false),
        remark("remark", "remark", "VARCHAR", false),
        runstate("runState", "runstate", "INTEGER", false),
        serverPort("server_port", "serverPort", "VARCHAR", false),
        fileConfigContent("file_config_content", "fileConfigContent", "LONGVARCHAR", false),
        flumeMonitorContent("flume_monitor_content", "flumeMonitorContent", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_config
     *
     * @mbg.generated
     */
    public enum Runstate {
        RUNING(new Integer("1"), "已开启"),
        UNOPENED(new Integer("2"), "未开启"),
        PUSHED(new Integer("3"), "已接收请求"),
        STARTING(new Integer("4"), "正在启动"),
        CREATEPROFILE(new Integer("5"), "创建配置文件"),
        CREATESCRIPTS(new Integer("6"), "创建脚本"),
        EXECSCRIPTS(new Integer("7"), "执行脚本"),
        FAIL(new Integer("8"), "失败"),
        PUSHING(new Integer("9"), "开始推送"),
        EXCEPTION(new Integer("10"), "启动异常"),
        RESTART(new Integer("11"), "重启"),
        RESTARTING(new Integer("12"), "正在重启"),
        PORTMONITORINGEXCEPTION(new Integer("13"), "端口监控异常");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final Integer value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        Runstate(Integer value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public Integer getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public Integer value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_config
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }
}