package com.qmtec.servicecore.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class DataModelRelationColumn implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dataModel_Column.dataModel_id
     *
     * @mbg.generated
     */
    private String datamodelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dataModel_Column.column_id
     *
     * @mbg.generated
     */
    private String columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dataModel_Column.dataModel_id
     *
     * @return the value of t_dataModel_Column.dataModel_id
     *
     * @mbg.generated
     */
    public String getDatamodelId() {
        return datamodelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dataModel_Column.dataModel_id
     *
     * @param datamodelId the value for t_dataModel_Column.dataModel_id
     *
     * @mbg.generated
     */
    public void setDatamodelId(String datamodelId) {
        this.datamodelId = datamodelId == null ? null : datamodelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dataModel_Column.column_id
     *
     * @return the value of t_dataModel_Column.column_id
     *
     * @mbg.generated
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dataModel_Column.column_id
     *
     * @param columnId the value for t_dataModel_Column.column_id
     *
     * @mbg.generated
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", datamodelId=").append(datamodelId);
        sb.append(", columnId=").append(columnId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    @Override
    public DataModelRelationColumn clone() throws CloneNotSupportedException {
        return (DataModelRelationColumn) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    public static DataModelRelationColumn.Builder builder() {
        return new DataModelRelationColumn.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private DataModelRelationColumn obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new DataModelRelationColumn();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_dataModel_Column.dataModel_id
         *
         * @param datamodelId the value for t_dataModel_Column.dataModel_id
         *
         * @mbg.generated
         */
        public Builder datamodelId(String datamodelId) {
            obj.setDatamodelId(datamodelId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_dataModel_Column.column_id
         *
         * @param columnId the value for t_dataModel_Column.column_id
         *
         * @mbg.generated
         */
        public Builder columnId(String columnId) {
            obj.setColumnId(columnId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public DataModelRelationColumn build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    public enum Column {
        datamodelId("dataModel_id", "datamodelId", "VARCHAR", false),
        columnId("column_id", "columnId", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_dataModel_Column
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}