package com.qmtec.servicecore.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class ResourceDB implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.startup_time
     *
     * @mbg.generated
     */
    private Date startupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.database_type
     *
     * @mbg.generated
     */
    private Integer databaseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resourceDB.define
     *
     * @mbg.generated
     */
    private String define;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.id
     *
     * @return the value of t_resourceDB.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.id
     *
     * @param id the value for t_resourceDB.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.name
     *
     * @return the value of t_resourceDB.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.name
     *
     * @param name the value for t_resourceDB.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.create_time
     *
     * @return the value of t_resourceDB.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.create_time
     *
     * @param createTime the value for t_resourceDB.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.modify_time
     *
     * @return the value of t_resourceDB.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.modify_time
     *
     * @param modifyTime the value for t_resourceDB.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.startup_time
     *
     * @return the value of t_resourceDB.startup_time
     *
     * @mbg.generated
     */
    public Date getStartupTime() {
        return startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.startup_time
     *
     * @param startupTime the value for t_resourceDB.startup_time
     *
     * @mbg.generated
     */
    public void setStartupTime(Date startupTime) {
        this.startupTime = startupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.remark
     *
     * @return the value of t_resourceDB.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.remark
     *
     * @param remark the value for t_resourceDB.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.database_type
     *
     * @return the value of t_resourceDB.database_type
     *
     * @mbg.generated
     */
    public Integer getDatabaseType() {
        return databaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.database_type
     *
     * @param databaseType the value for t_resourceDB.database_type
     *
     * @mbg.generated
     */
    public void setDatabaseType(Integer databaseType) {
        this.databaseType = databaseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resourceDB.define
     *
     * @return the value of t_resourceDB.define
     *
     * @mbg.generated
     */
    public String getDefine() {
        return define;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resourceDB.define
     *
     * @param define the value for t_resourceDB.define
     *
     * @mbg.generated
     */
    public void setDefine(String define) {
        this.define = define == null ? null : define.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", startupTime=").append(startupTime);
        sb.append(", remark=").append(remark);
        sb.append(", databaseType=").append(databaseType);
        sb.append(", define=").append(define);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    @Override
    public ResourceDB clone() throws CloneNotSupportedException {
        return (ResourceDB) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    public static ResourceDB.Builder builder() {
        return new ResourceDB.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private ResourceDB obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new ResourceDB();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.id
         *
         * @param id the value for t_resourceDB.id
         *
         * @mbg.generated
         */
        public Builder id(String id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.name
         *
         * @param name the value for t_resourceDB.name
         *
         * @mbg.generated
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.create_time
         *
         * @param createTime the value for t_resourceDB.create_time
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.modify_time
         *
         * @param modifyTime the value for t_resourceDB.modify_time
         *
         * @mbg.generated
         */
        public Builder modifyTime(Date modifyTime) {
            obj.setModifyTime(modifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.startup_time
         *
         * @param startupTime the value for t_resourceDB.startup_time
         *
         * @mbg.generated
         */
        public Builder startupTime(Date startupTime) {
            obj.setStartupTime(startupTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.remark
         *
         * @param remark the value for t_resourceDB.remark
         *
         * @mbg.generated
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.database_type
         *
         * @param databaseType the value for t_resourceDB.database_type
         *
         * @mbg.generated
         */
        public Builder databaseType(Integer databaseType) {
            obj.setDatabaseType(databaseType);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_resourceDB.define
         *
         * @param define the value for t_resourceDB.define
         *
         * @mbg.generated
         */
        public Builder define(String define) {
            obj.setDefine(define);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public ResourceDB build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        name("name", "name", "VARCHAR", true),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        startupTime("startup_time", "startupTime", "TIMESTAMP", false),
        remark("remark", "remark", "VARCHAR", false),
        databaseType("database_type", "databaseType", "INTEGER", false),
        define("define", "define", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_resourceDB
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}