package com.qmtec.servicecore.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class SinkInfo implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.component_name
     *
     * @mbg.generated
     */
    private String componentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.ip_addr
     *
     * @mbg.generated
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.connection_created_count
     *
     * @mbg.generated
     */
    private String connectionCreatedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.batch_complete_count
     *
     * @mbg.generated
     */
    private String batchCompleteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.batch_empty_count
     *
     * @mbg.generated
     */
    private String batchEmptyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.event_drainAttempt_count
     *
     * @mbg.generated
     */
    private String eventDrainattemptCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.batch_underflow_count
     *
     * @mbg.generated
     */
    private String batchUnderflowCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.connection_failed_count
     *
     * @mbg.generated
     */
    private String connectionFailedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.connection_closed_count
     *
     * @mbg.generated
     */
    private String connectionClosedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.rollback_count
     *
     * @mbg.generated
     */
    private String rollbackCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.event_drain_success_count
     *
     * @mbg.generated
     */
    private String eventDrainSuccessCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.kafka_event_sendTimer
     *
     * @mbg.generated
     */
    private String kafkaEventSendtimer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.run_state
     *
     * @mbg.generated
     */
    private Integer runState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.event_write_fail
     *
     * @mbg.generated
     */
    private String eventWriteFail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sinkInfo.channel_read_fail
     *
     * @mbg.generated
     */
    private String channelReadFail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.id
     *
     * @return the value of t_flume_sinkInfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.id
     *
     * @param id the value for t_flume_sinkInfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.component_name
     *
     * @return the value of t_flume_sinkInfo.component_name
     *
     * @mbg.generated
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.component_name
     *
     * @param componentName the value for t_flume_sinkInfo.component_name
     *
     * @mbg.generated
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.ip_addr
     *
     * @return the value of t_flume_sinkInfo.ip_addr
     *
     * @mbg.generated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.ip_addr
     *
     * @param ipAddr the value for t_flume_sinkInfo.ip_addr
     *
     * @mbg.generated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.start_time
     *
     * @return the value of t_flume_sinkInfo.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.start_time
     *
     * @param startTime the value for t_flume_sinkInfo.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.connection_created_count
     *
     * @return the value of t_flume_sinkInfo.connection_created_count
     *
     * @mbg.generated
     */
    public String getConnectionCreatedCount() {
        return connectionCreatedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.connection_created_count
     *
     * @param connectionCreatedCount the value for t_flume_sinkInfo.connection_created_count
     *
     * @mbg.generated
     */
    public void setConnectionCreatedCount(String connectionCreatedCount) {
        this.connectionCreatedCount = connectionCreatedCount == null ? null : connectionCreatedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.batch_complete_count
     *
     * @return the value of t_flume_sinkInfo.batch_complete_count
     *
     * @mbg.generated
     */
    public String getBatchCompleteCount() {
        return batchCompleteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.batch_complete_count
     *
     * @param batchCompleteCount the value for t_flume_sinkInfo.batch_complete_count
     *
     * @mbg.generated
     */
    public void setBatchCompleteCount(String batchCompleteCount) {
        this.batchCompleteCount = batchCompleteCount == null ? null : batchCompleteCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.batch_empty_count
     *
     * @return the value of t_flume_sinkInfo.batch_empty_count
     *
     * @mbg.generated
     */
    public String getBatchEmptyCount() {
        return batchEmptyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.batch_empty_count
     *
     * @param batchEmptyCount the value for t_flume_sinkInfo.batch_empty_count
     *
     * @mbg.generated
     */
    public void setBatchEmptyCount(String batchEmptyCount) {
        this.batchEmptyCount = batchEmptyCount == null ? null : batchEmptyCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.event_drainAttempt_count
     *
     * @return the value of t_flume_sinkInfo.event_drainAttempt_count
     *
     * @mbg.generated
     */
    public String getEventDrainattemptCount() {
        return eventDrainattemptCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.event_drainAttempt_count
     *
     * @param eventDrainattemptCount the value for t_flume_sinkInfo.event_drainAttempt_count
     *
     * @mbg.generated
     */
    public void setEventDrainattemptCount(String eventDrainattemptCount) {
        this.eventDrainattemptCount = eventDrainattemptCount == null ? null : eventDrainattemptCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.batch_underflow_count
     *
     * @return the value of t_flume_sinkInfo.batch_underflow_count
     *
     * @mbg.generated
     */
    public String getBatchUnderflowCount() {
        return batchUnderflowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.batch_underflow_count
     *
     * @param batchUnderflowCount the value for t_flume_sinkInfo.batch_underflow_count
     *
     * @mbg.generated
     */
    public void setBatchUnderflowCount(String batchUnderflowCount) {
        this.batchUnderflowCount = batchUnderflowCount == null ? null : batchUnderflowCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.connection_failed_count
     *
     * @return the value of t_flume_sinkInfo.connection_failed_count
     *
     * @mbg.generated
     */
    public String getConnectionFailedCount() {
        return connectionFailedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.connection_failed_count
     *
     * @param connectionFailedCount the value for t_flume_sinkInfo.connection_failed_count
     *
     * @mbg.generated
     */
    public void setConnectionFailedCount(String connectionFailedCount) {
        this.connectionFailedCount = connectionFailedCount == null ? null : connectionFailedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.connection_closed_count
     *
     * @return the value of t_flume_sinkInfo.connection_closed_count
     *
     * @mbg.generated
     */
    public String getConnectionClosedCount() {
        return connectionClosedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.connection_closed_count
     *
     * @param connectionClosedCount the value for t_flume_sinkInfo.connection_closed_count
     *
     * @mbg.generated
     */
    public void setConnectionClosedCount(String connectionClosedCount) {
        this.connectionClosedCount = connectionClosedCount == null ? null : connectionClosedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.rollback_count
     *
     * @return the value of t_flume_sinkInfo.rollback_count
     *
     * @mbg.generated
     */
    public String getRollbackCount() {
        return rollbackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.rollback_count
     *
     * @param rollbackCount the value for t_flume_sinkInfo.rollback_count
     *
     * @mbg.generated
     */
    public void setRollbackCount(String rollbackCount) {
        this.rollbackCount = rollbackCount == null ? null : rollbackCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.event_drain_success_count
     *
     * @return the value of t_flume_sinkInfo.event_drain_success_count
     *
     * @mbg.generated
     */
    public String getEventDrainSuccessCount() {
        return eventDrainSuccessCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.event_drain_success_count
     *
     * @param eventDrainSuccessCount the value for t_flume_sinkInfo.event_drain_success_count
     *
     * @mbg.generated
     */
    public void setEventDrainSuccessCount(String eventDrainSuccessCount) {
        this.eventDrainSuccessCount = eventDrainSuccessCount == null ? null : eventDrainSuccessCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.kafka_event_sendTimer
     *
     * @return the value of t_flume_sinkInfo.kafka_event_sendTimer
     *
     * @mbg.generated
     */
    public String getKafkaEventSendtimer() {
        return kafkaEventSendtimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.kafka_event_sendTimer
     *
     * @param kafkaEventSendtimer the value for t_flume_sinkInfo.kafka_event_sendTimer
     *
     * @mbg.generated
     */
    public void setKafkaEventSendtimer(String kafkaEventSendtimer) {
        this.kafkaEventSendtimer = kafkaEventSendtimer == null ? null : kafkaEventSendtimer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.run_state
     *
     * @return the value of t_flume_sinkInfo.run_state
     *
     * @mbg.generated
     */
    public Integer getRunState() {
        return runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.run_state
     *
     * @param runState the value for t_flume_sinkInfo.run_state
     *
     * @mbg.generated
     */
    public void setRunState(Integer runState) {
        this.runState = runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.delete_flag
     *
     * @return the value of t_flume_sinkInfo.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.delete_flag
     *
     * @param deleteFlag the value for t_flume_sinkInfo.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.create_time
     *
     * @return the value of t_flume_sinkInfo.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.create_time
     *
     * @param createTime the value for t_flume_sinkInfo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.modify_time
     *
     * @return the value of t_flume_sinkInfo.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.modify_time
     *
     * @param modifyTime the value for t_flume_sinkInfo.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.event_write_fail
     *
     * @return the value of t_flume_sinkInfo.event_write_fail
     *
     * @mbg.generated
     */
    public String getEventWriteFail() {
        return eventWriteFail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.event_write_fail
     *
     * @param eventWriteFail the value for t_flume_sinkInfo.event_write_fail
     *
     * @mbg.generated
     */
    public void setEventWriteFail(String eventWriteFail) {
        this.eventWriteFail = eventWriteFail == null ? null : eventWriteFail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sinkInfo.channel_read_fail
     *
     * @return the value of t_flume_sinkInfo.channel_read_fail
     *
     * @mbg.generated
     */
    public String getChannelReadFail() {
        return channelReadFail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sinkInfo.channel_read_fail
     *
     * @param channelReadFail the value for t_flume_sinkInfo.channel_read_fail
     *
     * @mbg.generated
     */
    public void setChannelReadFail(String channelReadFail) {
        this.channelReadFail = channelReadFail == null ? null : channelReadFail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", componentName=").append(componentName);
        sb.append(", ipAddr=").append(ipAddr);
        sb.append(", startTime=").append(startTime);
        sb.append(", connectionCreatedCount=").append(connectionCreatedCount);
        sb.append(", batchCompleteCount=").append(batchCompleteCount);
        sb.append(", batchEmptyCount=").append(batchEmptyCount);
        sb.append(", eventDrainattemptCount=").append(eventDrainattemptCount);
        sb.append(", batchUnderflowCount=").append(batchUnderflowCount);
        sb.append(", connectionFailedCount=").append(connectionFailedCount);
        sb.append(", connectionClosedCount=").append(connectionClosedCount);
        sb.append(", rollbackCount=").append(rollbackCount);
        sb.append(", eventDrainSuccessCount=").append(eventDrainSuccessCount);
        sb.append(", kafkaEventSendtimer=").append(kafkaEventSendtimer);
        sb.append(", runState=").append(runState);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", eventWriteFail=").append(eventWriteFail);
        sb.append(", channelReadFail=").append(channelReadFail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    @Override
    public SinkInfo clone() throws CloneNotSupportedException {
        return (SinkInfo) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    public static SinkInfo.Builder builder() {
        return new SinkInfo.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private SinkInfo obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new SinkInfo();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.id
         *
         * @param id the value for t_flume_sinkInfo.id
         *
         * @mbg.generated
         */
        public Builder id(String id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.component_name
         *
         * @param componentName the value for t_flume_sinkInfo.component_name
         *
         * @mbg.generated
         */
        public Builder componentName(String componentName) {
            obj.setComponentName(componentName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.ip_addr
         *
         * @param ipAddr the value for t_flume_sinkInfo.ip_addr
         *
         * @mbg.generated
         */
        public Builder ipAddr(String ipAddr) {
            obj.setIpAddr(ipAddr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.start_time
         *
         * @param startTime the value for t_flume_sinkInfo.start_time
         *
         * @mbg.generated
         */
        public Builder startTime(Date startTime) {
            obj.setStartTime(startTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.connection_created_count
         *
         * @param connectionCreatedCount the value for t_flume_sinkInfo.connection_created_count
         *
         * @mbg.generated
         */
        public Builder connectionCreatedCount(String connectionCreatedCount) {
            obj.setConnectionCreatedCount(connectionCreatedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.batch_complete_count
         *
         * @param batchCompleteCount the value for t_flume_sinkInfo.batch_complete_count
         *
         * @mbg.generated
         */
        public Builder batchCompleteCount(String batchCompleteCount) {
            obj.setBatchCompleteCount(batchCompleteCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.batch_empty_count
         *
         * @param batchEmptyCount the value for t_flume_sinkInfo.batch_empty_count
         *
         * @mbg.generated
         */
        public Builder batchEmptyCount(String batchEmptyCount) {
            obj.setBatchEmptyCount(batchEmptyCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.event_drainAttempt_count
         *
         * @param eventDrainattemptCount the value for t_flume_sinkInfo.event_drainAttempt_count
         *
         * @mbg.generated
         */
        public Builder eventDrainattemptCount(String eventDrainattemptCount) {
            obj.setEventDrainattemptCount(eventDrainattemptCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.batch_underflow_count
         *
         * @param batchUnderflowCount the value for t_flume_sinkInfo.batch_underflow_count
         *
         * @mbg.generated
         */
        public Builder batchUnderflowCount(String batchUnderflowCount) {
            obj.setBatchUnderflowCount(batchUnderflowCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.connection_failed_count
         *
         * @param connectionFailedCount the value for t_flume_sinkInfo.connection_failed_count
         *
         * @mbg.generated
         */
        public Builder connectionFailedCount(String connectionFailedCount) {
            obj.setConnectionFailedCount(connectionFailedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.connection_closed_count
         *
         * @param connectionClosedCount the value for t_flume_sinkInfo.connection_closed_count
         *
         * @mbg.generated
         */
        public Builder connectionClosedCount(String connectionClosedCount) {
            obj.setConnectionClosedCount(connectionClosedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.rollback_count
         *
         * @param rollbackCount the value for t_flume_sinkInfo.rollback_count
         *
         * @mbg.generated
         */
        public Builder rollbackCount(String rollbackCount) {
            obj.setRollbackCount(rollbackCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.event_drain_success_count
         *
         * @param eventDrainSuccessCount the value for t_flume_sinkInfo.event_drain_success_count
         *
         * @mbg.generated
         */
        public Builder eventDrainSuccessCount(String eventDrainSuccessCount) {
            obj.setEventDrainSuccessCount(eventDrainSuccessCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.kafka_event_sendTimer
         *
         * @param kafkaEventSendtimer the value for t_flume_sinkInfo.kafka_event_sendTimer
         *
         * @mbg.generated
         */
        public Builder kafkaEventSendtimer(String kafkaEventSendtimer) {
            obj.setKafkaEventSendtimer(kafkaEventSendtimer);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.run_state
         *
         * @param runState the value for t_flume_sinkInfo.run_state
         *
         * @mbg.generated
         */
        public Builder runState(Integer runState) {
            obj.setRunState(runState);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.delete_flag
         *
         * @param deleteFlag the value for t_flume_sinkInfo.delete_flag
         *
         * @mbg.generated
         */
        public Builder deleteFlag(Integer deleteFlag) {
            obj.setDeleteFlag(deleteFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.create_time
         *
         * @param createTime the value for t_flume_sinkInfo.create_time
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.modify_time
         *
         * @param modifyTime the value for t_flume_sinkInfo.modify_time
         *
         * @mbg.generated
         */
        public Builder modifyTime(Date modifyTime) {
            obj.setModifyTime(modifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.event_write_fail
         *
         * @param eventWriteFail the value for t_flume_sinkInfo.event_write_fail
         *
         * @mbg.generated
         */
        public Builder eventWriteFail(String eventWriteFail) {
            obj.setEventWriteFail(eventWriteFail);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sinkInfo.channel_read_fail
         *
         * @param channelReadFail the value for t_flume_sinkInfo.channel_read_fail
         *
         * @mbg.generated
         */
        public Builder channelReadFail(String channelReadFail) {
            obj.setChannelReadFail(channelReadFail);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public SinkInfo build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        componentName("component_name", "componentName", "VARCHAR", false),
        ipAddr("ip_addr", "ipAddr", "VARCHAR", false),
        startTime("start_time", "startTime", "TIMESTAMP", false),
        connectionCreatedCount("connection_created_count", "connectionCreatedCount", "VARCHAR", false),
        batchCompleteCount("batch_complete_count", "batchCompleteCount", "VARCHAR", false),
        batchEmptyCount("batch_empty_count", "batchEmptyCount", "VARCHAR", false),
        eventDrainattemptCount("event_drainAttempt_count", "eventDrainattemptCount", "VARCHAR", false),
        batchUnderflowCount("batch_underflow_count", "batchUnderflowCount", "VARCHAR", false),
        connectionFailedCount("connection_failed_count", "connectionFailedCount", "VARCHAR", false),
        connectionClosedCount("connection_closed_count", "connectionClosedCount", "VARCHAR", false),
        rollbackCount("rollback_count", "rollbackCount", "VARCHAR", false),
        eventDrainSuccessCount("event_drain_success_count", "eventDrainSuccessCount", "VARCHAR", false),
        kafkaEventSendtimer("kafka_event_sendTimer", "kafkaEventSendtimer", "VARCHAR", false),
        runState("run_state", "runState", "INTEGER", false),
        deleteFlag("delete_flag", "deleteFlag", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        eventWriteFail("event_write_fail", "eventWriteFail", "VARCHAR", false),
        channelReadFail("channel_read_fail", "channelReadFail", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_sinkInfo
     *
     * @mbg.generated
     */
    public enum RunState {
        RUNING(new Integer("1"), "已开启"),
        CLOSE(new Integer("2"), "关闭"),
        PORTMONITORINGEXCEPTION(new Integer("3"), "端口监控异常");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final Integer value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        RunState(Integer value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public Integer getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public Integer value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sinkInfo
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }
}