package com.qmtec.servicecore.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class SourceInfo implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.component_name
     *
     * @mbg.generated
     */
    private String componentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.ip_addr
     *
     * @mbg.generated
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.current_throughput
     *
     * @mbg.generated
     */
    private String currentThroughput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.max_throughput
     *
     * @mbg.generated
     */
    private String maxThroughput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.event_count
     *
     * @mbg.generated
     */
    private String eventCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.average_throughput
     *
     * @mbg.generated
     */
    private String averageThroughput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.run_state
     *
     * @mbg.generated
     */
    private Integer runState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.event_get_timer
     *
     * @mbg.generated
     */
    private String eventGetTimer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.append_batch_accepted_count
     *
     * @mbg.generated
     */
    private String appendBatchAcceptedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.event_accepted_count
     *
     * @mbg.generated
     */
    private String eventAcceptedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.append_received_count
     *
     * @mbg.generated
     */
    private String appendReceivedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.append_batch_received_count
     *
     * @mbg.generated
     */
    private String appendBatchReceivedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.kafka_commit_timer
     *
     * @mbg.generated
     */
    private String kafkaCommitTimer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.event_received_count
     *
     * @mbg.generated
     */
    private String eventReceivedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.append_accepted_count
     *
     * @mbg.generated
     */
    private String appendAcceptedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.open_connection_count
     *
     * @mbg.generated
     */
    private String openConnectionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flume_sourcesInfo.kafka_empty_count
     *
     * @mbg.generated
     */
    private String kafkaEmptyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.id
     *
     * @return the value of t_flume_sourcesInfo.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.id
     *
     * @param id the value for t_flume_sourcesInfo.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.component_name
     *
     * @return the value of t_flume_sourcesInfo.component_name
     *
     * @mbg.generated
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.component_name
     *
     * @param componentName the value for t_flume_sourcesInfo.component_name
     *
     * @mbg.generated
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName == null ? null : componentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.ip_addr
     *
     * @return the value of t_flume_sourcesInfo.ip_addr
     *
     * @mbg.generated
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.ip_addr
     *
     * @param ipAddr the value for t_flume_sourcesInfo.ip_addr
     *
     * @mbg.generated
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.current_throughput
     *
     * @return the value of t_flume_sourcesInfo.current_throughput
     *
     * @mbg.generated
     */
    public String getCurrentThroughput() {
        return currentThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.current_throughput
     *
     * @param currentThroughput the value for t_flume_sourcesInfo.current_throughput
     *
     * @mbg.generated
     */
    public void setCurrentThroughput(String currentThroughput) {
        this.currentThroughput = currentThroughput == null ? null : currentThroughput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.max_throughput
     *
     * @return the value of t_flume_sourcesInfo.max_throughput
     *
     * @mbg.generated
     */
    public String getMaxThroughput() {
        return maxThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.max_throughput
     *
     * @param maxThroughput the value for t_flume_sourcesInfo.max_throughput
     *
     * @mbg.generated
     */
    public void setMaxThroughput(String maxThroughput) {
        this.maxThroughput = maxThroughput == null ? null : maxThroughput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.event_count
     *
     * @return the value of t_flume_sourcesInfo.event_count
     *
     * @mbg.generated
     */
    public String getEventCount() {
        return eventCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.event_count
     *
     * @param eventCount the value for t_flume_sourcesInfo.event_count
     *
     * @mbg.generated
     */
    public void setEventCount(String eventCount) {
        this.eventCount = eventCount == null ? null : eventCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.average_throughput
     *
     * @return the value of t_flume_sourcesInfo.average_throughput
     *
     * @mbg.generated
     */
    public String getAverageThroughput() {
        return averageThroughput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.average_throughput
     *
     * @param averageThroughput the value for t_flume_sourcesInfo.average_throughput
     *
     * @mbg.generated
     */
    public void setAverageThroughput(String averageThroughput) {
        this.averageThroughput = averageThroughput == null ? null : averageThroughput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.run_state
     *
     * @return the value of t_flume_sourcesInfo.run_state
     *
     * @mbg.generated
     */
    public Integer getRunState() {
        return runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.run_state
     *
     * @param runState the value for t_flume_sourcesInfo.run_state
     *
     * @mbg.generated
     */
    public void setRunState(Integer runState) {
        this.runState = runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.delete_flag
     *
     * @return the value of t_flume_sourcesInfo.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.delete_flag
     *
     * @param deleteFlag the value for t_flume_sourcesInfo.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.create_time
     *
     * @return the value of t_flume_sourcesInfo.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.create_time
     *
     * @param createTime the value for t_flume_sourcesInfo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.modify_time
     *
     * @return the value of t_flume_sourcesInfo.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.modify_time
     *
     * @param modifyTime the value for t_flume_sourcesInfo.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.event_get_timer
     *
     * @return the value of t_flume_sourcesInfo.event_get_timer
     *
     * @mbg.generated
     */
    public String getEventGetTimer() {
        return eventGetTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.event_get_timer
     *
     * @param eventGetTimer the value for t_flume_sourcesInfo.event_get_timer
     *
     * @mbg.generated
     */
    public void setEventGetTimer(String eventGetTimer) {
        this.eventGetTimer = eventGetTimer == null ? null : eventGetTimer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.append_batch_accepted_count
     *
     * @return the value of t_flume_sourcesInfo.append_batch_accepted_count
     *
     * @mbg.generated
     */
    public String getAppendBatchAcceptedCount() {
        return appendBatchAcceptedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.append_batch_accepted_count
     *
     * @param appendBatchAcceptedCount the value for t_flume_sourcesInfo.append_batch_accepted_count
     *
     * @mbg.generated
     */
    public void setAppendBatchAcceptedCount(String appendBatchAcceptedCount) {
        this.appendBatchAcceptedCount = appendBatchAcceptedCount == null ? null : appendBatchAcceptedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.event_accepted_count
     *
     * @return the value of t_flume_sourcesInfo.event_accepted_count
     *
     * @mbg.generated
     */
    public String getEventAcceptedCount() {
        return eventAcceptedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.event_accepted_count
     *
     * @param eventAcceptedCount the value for t_flume_sourcesInfo.event_accepted_count
     *
     * @mbg.generated
     */
    public void setEventAcceptedCount(String eventAcceptedCount) {
        this.eventAcceptedCount = eventAcceptedCount == null ? null : eventAcceptedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.append_received_count
     *
     * @return the value of t_flume_sourcesInfo.append_received_count
     *
     * @mbg.generated
     */
    public String getAppendReceivedCount() {
        return appendReceivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.append_received_count
     *
     * @param appendReceivedCount the value for t_flume_sourcesInfo.append_received_count
     *
     * @mbg.generated
     */
    public void setAppendReceivedCount(String appendReceivedCount) {
        this.appendReceivedCount = appendReceivedCount == null ? null : appendReceivedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.append_batch_received_count
     *
     * @return the value of t_flume_sourcesInfo.append_batch_received_count
     *
     * @mbg.generated
     */
    public String getAppendBatchReceivedCount() {
        return appendBatchReceivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.append_batch_received_count
     *
     * @param appendBatchReceivedCount the value for t_flume_sourcesInfo.append_batch_received_count
     *
     * @mbg.generated
     */
    public void setAppendBatchReceivedCount(String appendBatchReceivedCount) {
        this.appendBatchReceivedCount = appendBatchReceivedCount == null ? null : appendBatchReceivedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.kafka_commit_timer
     *
     * @return the value of t_flume_sourcesInfo.kafka_commit_timer
     *
     * @mbg.generated
     */
    public String getKafkaCommitTimer() {
        return kafkaCommitTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.kafka_commit_timer
     *
     * @param kafkaCommitTimer the value for t_flume_sourcesInfo.kafka_commit_timer
     *
     * @mbg.generated
     */
    public void setKafkaCommitTimer(String kafkaCommitTimer) {
        this.kafkaCommitTimer = kafkaCommitTimer == null ? null : kafkaCommitTimer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.event_received_count
     *
     * @return the value of t_flume_sourcesInfo.event_received_count
     *
     * @mbg.generated
     */
    public String getEventReceivedCount() {
        return eventReceivedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.event_received_count
     *
     * @param eventReceivedCount the value for t_flume_sourcesInfo.event_received_count
     *
     * @mbg.generated
     */
    public void setEventReceivedCount(String eventReceivedCount) {
        this.eventReceivedCount = eventReceivedCount == null ? null : eventReceivedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.append_accepted_count
     *
     * @return the value of t_flume_sourcesInfo.append_accepted_count
     *
     * @mbg.generated
     */
    public String getAppendAcceptedCount() {
        return appendAcceptedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.append_accepted_count
     *
     * @param appendAcceptedCount the value for t_flume_sourcesInfo.append_accepted_count
     *
     * @mbg.generated
     */
    public void setAppendAcceptedCount(String appendAcceptedCount) {
        this.appendAcceptedCount = appendAcceptedCount == null ? null : appendAcceptedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.open_connection_count
     *
     * @return the value of t_flume_sourcesInfo.open_connection_count
     *
     * @mbg.generated
     */
    public String getOpenConnectionCount() {
        return openConnectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.open_connection_count
     *
     * @param openConnectionCount the value for t_flume_sourcesInfo.open_connection_count
     *
     * @mbg.generated
     */
    public void setOpenConnectionCount(String openConnectionCount) {
        this.openConnectionCount = openConnectionCount == null ? null : openConnectionCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flume_sourcesInfo.kafka_empty_count
     *
     * @return the value of t_flume_sourcesInfo.kafka_empty_count
     *
     * @mbg.generated
     */
    public String getKafkaEmptyCount() {
        return kafkaEmptyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flume_sourcesInfo.kafka_empty_count
     *
     * @param kafkaEmptyCount the value for t_flume_sourcesInfo.kafka_empty_count
     *
     * @mbg.generated
     */
    public void setKafkaEmptyCount(String kafkaEmptyCount) {
        this.kafkaEmptyCount = kafkaEmptyCount == null ? null : kafkaEmptyCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", componentName=").append(componentName);
        sb.append(", ipAddr=").append(ipAddr);
        sb.append(", currentThroughput=").append(currentThroughput);
        sb.append(", maxThroughput=").append(maxThroughput);
        sb.append(", eventCount=").append(eventCount);
        sb.append(", averageThroughput=").append(averageThroughput);
        sb.append(", runState=").append(runState);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", eventGetTimer=").append(eventGetTimer);
        sb.append(", appendBatchAcceptedCount=").append(appendBatchAcceptedCount);
        sb.append(", eventAcceptedCount=").append(eventAcceptedCount);
        sb.append(", appendReceivedCount=").append(appendReceivedCount);
        sb.append(", appendBatchReceivedCount=").append(appendBatchReceivedCount);
        sb.append(", kafkaCommitTimer=").append(kafkaCommitTimer);
        sb.append(", eventReceivedCount=").append(eventReceivedCount);
        sb.append(", appendAcceptedCount=").append(appendAcceptedCount);
        sb.append(", openConnectionCount=").append(openConnectionCount);
        sb.append(", kafkaEmptyCount=").append(kafkaEmptyCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    @Override
    public SourceInfo clone() throws CloneNotSupportedException {
        return (SourceInfo) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    public static SourceInfo.Builder builder() {
        return new SourceInfo.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private SourceInfo obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new SourceInfo();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.id
         *
         * @param id the value for t_flume_sourcesInfo.id
         *
         * @mbg.generated
         */
        public Builder id(String id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.component_name
         *
         * @param componentName the value for t_flume_sourcesInfo.component_name
         *
         * @mbg.generated
         */
        public Builder componentName(String componentName) {
            obj.setComponentName(componentName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.ip_addr
         *
         * @param ipAddr the value for t_flume_sourcesInfo.ip_addr
         *
         * @mbg.generated
         */
        public Builder ipAddr(String ipAddr) {
            obj.setIpAddr(ipAddr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.current_throughput
         *
         * @param currentThroughput the value for t_flume_sourcesInfo.current_throughput
         *
         * @mbg.generated
         */
        public Builder currentThroughput(String currentThroughput) {
            obj.setCurrentThroughput(currentThroughput);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.max_throughput
         *
         * @param maxThroughput the value for t_flume_sourcesInfo.max_throughput
         *
         * @mbg.generated
         */
        public Builder maxThroughput(String maxThroughput) {
            obj.setMaxThroughput(maxThroughput);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.event_count
         *
         * @param eventCount the value for t_flume_sourcesInfo.event_count
         *
         * @mbg.generated
         */
        public Builder eventCount(String eventCount) {
            obj.setEventCount(eventCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.average_throughput
         *
         * @param averageThroughput the value for t_flume_sourcesInfo.average_throughput
         *
         * @mbg.generated
         */
        public Builder averageThroughput(String averageThroughput) {
            obj.setAverageThroughput(averageThroughput);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.run_state
         *
         * @param runState the value for t_flume_sourcesInfo.run_state
         *
         * @mbg.generated
         */
        public Builder runState(Integer runState) {
            obj.setRunState(runState);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.delete_flag
         *
         * @param deleteFlag the value for t_flume_sourcesInfo.delete_flag
         *
         * @mbg.generated
         */
        public Builder deleteFlag(Integer deleteFlag) {
            obj.setDeleteFlag(deleteFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.create_time
         *
         * @param createTime the value for t_flume_sourcesInfo.create_time
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.modify_time
         *
         * @param modifyTime the value for t_flume_sourcesInfo.modify_time
         *
         * @mbg.generated
         */
        public Builder modifyTime(Date modifyTime) {
            obj.setModifyTime(modifyTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.event_get_timer
         *
         * @param eventGetTimer the value for t_flume_sourcesInfo.event_get_timer
         *
         * @mbg.generated
         */
        public Builder eventGetTimer(String eventGetTimer) {
            obj.setEventGetTimer(eventGetTimer);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.append_batch_accepted_count
         *
         * @param appendBatchAcceptedCount the value for t_flume_sourcesInfo.append_batch_accepted_count
         *
         * @mbg.generated
         */
        public Builder appendBatchAcceptedCount(String appendBatchAcceptedCount) {
            obj.setAppendBatchAcceptedCount(appendBatchAcceptedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.event_accepted_count
         *
         * @param eventAcceptedCount the value for t_flume_sourcesInfo.event_accepted_count
         *
         * @mbg.generated
         */
        public Builder eventAcceptedCount(String eventAcceptedCount) {
            obj.setEventAcceptedCount(eventAcceptedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.append_received_count
         *
         * @param appendReceivedCount the value for t_flume_sourcesInfo.append_received_count
         *
         * @mbg.generated
         */
        public Builder appendReceivedCount(String appendReceivedCount) {
            obj.setAppendReceivedCount(appendReceivedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.append_batch_received_count
         *
         * @param appendBatchReceivedCount the value for t_flume_sourcesInfo.append_batch_received_count
         *
         * @mbg.generated
         */
        public Builder appendBatchReceivedCount(String appendBatchReceivedCount) {
            obj.setAppendBatchReceivedCount(appendBatchReceivedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.kafka_commit_timer
         *
         * @param kafkaCommitTimer the value for t_flume_sourcesInfo.kafka_commit_timer
         *
         * @mbg.generated
         */
        public Builder kafkaCommitTimer(String kafkaCommitTimer) {
            obj.setKafkaCommitTimer(kafkaCommitTimer);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.event_received_count
         *
         * @param eventReceivedCount the value for t_flume_sourcesInfo.event_received_count
         *
         * @mbg.generated
         */
        public Builder eventReceivedCount(String eventReceivedCount) {
            obj.setEventReceivedCount(eventReceivedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.append_accepted_count
         *
         * @param appendAcceptedCount the value for t_flume_sourcesInfo.append_accepted_count
         *
         * @mbg.generated
         */
        public Builder appendAcceptedCount(String appendAcceptedCount) {
            obj.setAppendAcceptedCount(appendAcceptedCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.open_connection_count
         *
         * @param openConnectionCount the value for t_flume_sourcesInfo.open_connection_count
         *
         * @mbg.generated
         */
        public Builder openConnectionCount(String openConnectionCount) {
            obj.setOpenConnectionCount(openConnectionCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_flume_sourcesInfo.kafka_empty_count
         *
         * @param kafkaEmptyCount the value for t_flume_sourcesInfo.kafka_empty_count
         *
         * @mbg.generated
         */
        public Builder kafkaEmptyCount(String kafkaEmptyCount) {
            obj.setKafkaEmptyCount(kafkaEmptyCount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public SourceInfo build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        componentName("component_name", "componentName", "VARCHAR", false),
        ipAddr("ip_addr", "ipAddr", "VARCHAR", false),
        currentThroughput("current_throughput", "currentThroughput", "VARCHAR", false),
        maxThroughput("max_throughput", "maxThroughput", "VARCHAR", false),
        eventCount("event_count", "eventCount", "VARCHAR", false),
        averageThroughput("average_throughput", "averageThroughput", "VARCHAR", false),
        runState("run_state", "runState", "INTEGER", false),
        deleteFlag("delete_flag", "deleteFlag", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        eventGetTimer("event_get_timer", "eventGetTimer", "VARCHAR", false),
        appendBatchAcceptedCount("append_batch_accepted_count", "appendBatchAcceptedCount", "VARCHAR", false),
        eventAcceptedCount("event_accepted_count", "eventAcceptedCount", "VARCHAR", false),
        appendReceivedCount("append_received_count", "appendReceivedCount", "VARCHAR", false),
        appendBatchReceivedCount("append_batch_received_count", "appendBatchReceivedCount", "VARCHAR", false),
        kafkaCommitTimer("kafka_commit_timer", "kafkaCommitTimer", "VARCHAR", false),
        eventReceivedCount("event_received_count", "eventReceivedCount", "VARCHAR", false),
        appendAcceptedCount("append_accepted_count", "appendAcceptedCount", "VARCHAR", false),
        openConnectionCount("open_connection_count", "openConnectionCount", "VARCHAR", false),
        kafkaEmptyCount("kafka_empty_count", "kafkaEmptyCount", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_flume_sourcesInfo
     *
     * @mbg.generated
     */
    public enum RunState {
        RUNING(new Integer("1"), "已开启"),
        CLOSE(new Integer("2"), "关闭"),
        PORTMONITORINGEXCEPTION(new Integer("3"), "端口监控异常");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final Integer value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        RunState(Integer value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public Integer getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public Integer value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_flume_sourcesInfo
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }
}