package com.qmtec.servicecore.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class TbSerdeParams implements Cloneable, Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERDE_PARAMS.SERDE_ID
     *
     * @mbg.generated
     */
    private Long serdeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERDE_PARAMS.PARAM_KEY
     *
     * @mbg.generated
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SERDE_PARAMS.PARAM_VALUE
     *
     * @mbg.generated
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERDE_PARAMS.SERDE_ID
     *
     * @return the value of SERDE_PARAMS.SERDE_ID
     *
     * @mbg.generated
     */
    public Long getSerdeId() {
        return serdeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERDE_PARAMS.SERDE_ID
     *
     * @param serdeId the value for SERDE_PARAMS.SERDE_ID
     *
     * @mbg.generated
     */
    public void setSerdeId(Long serdeId) {
        this.serdeId = serdeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERDE_PARAMS.PARAM_KEY
     *
     * @return the value of SERDE_PARAMS.PARAM_KEY
     *
     * @mbg.generated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERDE_PARAMS.PARAM_KEY
     *
     * @param paramKey the value for SERDE_PARAMS.PARAM_KEY
     *
     * @mbg.generated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey == null ? null : paramKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERDE_PARAMS.PARAM_VALUE
     *
     * @return the value of SERDE_PARAMS.PARAM_VALUE
     *
     * @mbg.generated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERDE_PARAMS.PARAM_VALUE
     *
     * @param paramValue the value for SERDE_PARAMS.PARAM_VALUE
     *
     * @mbg.generated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serdeId=").append(serdeId);
        sb.append(", paramKey=").append(paramKey);
        sb.append(", paramValue=").append(paramValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    @Override
    public TbSerdeParams clone() throws CloneNotSupportedException {
        return (TbSerdeParams) super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    public static TbSerdeParams.Builder builder() {
        return new TbSerdeParams.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private TbSerdeParams obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new TbSerdeParams();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column SERDE_PARAMS.SERDE_ID
         *
         * @param serdeId the value for SERDE_PARAMS.SERDE_ID
         *
         * @mbg.generated
         */
        public Builder serdeId(Long serdeId) {
            obj.setSerdeId(serdeId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column SERDE_PARAMS.PARAM_KEY
         *
         * @param paramKey the value for SERDE_PARAMS.PARAM_KEY
         *
         * @mbg.generated
         */
        public Builder paramKey(String paramKey) {
            obj.setParamKey(paramKey);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column SERDE_PARAMS.PARAM_VALUE
         *
         * @param paramValue the value for SERDE_PARAMS.PARAM_VALUE
         *
         * @mbg.generated
         */
        public Builder paramValue(String paramValue) {
            obj.setParamValue(paramValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public TbSerdeParams build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table SERDE_PARAMS
     *
     * @mbg.generated
     */
    public enum Column {
        serdeId("SERDE_ID", "serdeId", "BIGINT", false),
        paramKey("PARAM_KEY", "paramKey", "VARCHAR", false),
        paramValue("PARAM_VALUE", "paramValue", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table SERDE_PARAMS
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}