package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.DataModelRelationColumn;
import com.qmtec.servicecore.entity.example.DataModelRelationColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataModelRelationColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    long countByExample(DataModelRelationColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    int deleteByExample(DataModelRelationColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    int insert(DataModelRelationColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") DataModelRelationColumn record, @Param("selective") DataModelRelationColumn.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    DataModelRelationColumn selectOneByExample(DataModelRelationColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    DataModelRelationColumn selectOneByExampleSelective(@Param("example") DataModelRelationColumnExample example, @Param("selective") DataModelRelationColumn.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    List<DataModelRelationColumn> selectByExampleSelective(@Param("example") DataModelRelationColumnExample example, @Param("selective") DataModelRelationColumn.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    List<DataModelRelationColumn> selectByExample(DataModelRelationColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DataModelRelationColumn record, @Param("example") DataModelRelationColumnExample example, @Param("selective") DataModelRelationColumn.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dataModel_Column
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DataModelRelationColumn record, @Param("example") DataModelRelationColumnExample example);
}