package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.FlumeRelationChannel;
import com.qmtec.servicecore.entity.example.FlumeRelationChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlumeRelationChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    long countByExample(FlumeRelationChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    int deleteByExample(FlumeRelationChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    int insert(FlumeRelationChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FlumeRelationChannel record, @Param("selective") FlumeRelationChannel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    FlumeRelationChannel selectOneByExample(FlumeRelationChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    FlumeRelationChannel selectOneByExampleSelective(@Param("example") FlumeRelationChannelExample example, @Param("selective") FlumeRelationChannel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationChannel> selectByExampleSelective(@Param("example") FlumeRelationChannelExample example, @Param("selective") FlumeRelationChannel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationChannel> selectByExample(FlumeRelationChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlumeRelationChannel record, @Param("example") FlumeRelationChannelExample example, @Param("selective") FlumeRelationChannel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_ChannelInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlumeRelationChannel record, @Param("example") FlumeRelationChannelExample example);
}