package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.FlumeRelationSources;
import com.qmtec.servicecore.entity.example.FlumeRelationSourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlumeRelationSourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    long countByExample(FlumeRelationSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    int deleteByExample(FlumeRelationSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    int insert(FlumeRelationSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FlumeRelationSources record, @Param("selective") FlumeRelationSources.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    FlumeRelationSources selectOneByExample(FlumeRelationSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    FlumeRelationSources selectOneByExampleSelective(@Param("example") FlumeRelationSourcesExample example, @Param("selective") FlumeRelationSources.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationSources> selectByExampleSelective(@Param("example") FlumeRelationSourcesExample example, @Param("selective") FlumeRelationSources.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationSources> selectByExample(FlumeRelationSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlumeRelationSources record, @Param("example") FlumeRelationSourcesExample example, @Param("selective") FlumeRelationSources.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sourcesInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlumeRelationSources record, @Param("example") FlumeRelationSourcesExample example);
}