package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.FlumeRelationSink;
import com.qmtec.servicecore.entity.example.FlumeRelationSinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlumeRelationSinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    long countByExample(FlumeRelationSinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    int deleteByExample(FlumeRelationSinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    int insert(FlumeRelationSink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FlumeRelationSink record, @Param("selective") FlumeRelationSink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    FlumeRelationSink selectOneByExample(FlumeRelationSinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    FlumeRelationSink selectOneByExampleSelective(@Param("example") FlumeRelationSinkExample example, @Param("selective") FlumeRelationSink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationSink> selectByExampleSelective(@Param("example") FlumeRelationSinkExample example, @Param("selective") FlumeRelationSink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    List<FlumeRelationSink> selectByExample(FlumeRelationSinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlumeRelationSink record, @Param("example") FlumeRelationSinkExample example, @Param("selective") FlumeRelationSink.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flumeCofig_sinkInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlumeRelationSink record, @Param("example") FlumeRelationSinkExample example);
}