package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.ResourceDB;
import com.qmtec.servicecore.entity.example.ResourceDBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceDBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    long countByExample(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int deleteByExample(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int insert(ResourceDB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") ResourceDB record, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    ResourceDB selectOneByExample(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    ResourceDB selectOneByExampleSelective(@Param("example") ResourceDBExample example, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    ResourceDB selectOneByExampleWithBLOBs(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    List<ResourceDB> selectByExampleSelective(@Param("example") ResourceDBExample example, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    List<ResourceDB> selectByExampleWithBLOBs(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    List<ResourceDB> selectByExample(ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    ResourceDB selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    ResourceDB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResourceDB record, @Param("example") ResourceDBExample example, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ResourceDB record, @Param("example") ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResourceDB record, @Param("example") ResourceDBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") ResourceDB record, @Param("selective") ResourceDB.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ResourceDB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resourceDB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceDB record);
}