package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.TbDBS;
import com.qmtec.servicecore.entity.example.TbDBSExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDBSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    long countByExample(TbDBSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int deleteByExample(TbDBSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int insert(TbDBS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TbDBS record, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    TbDBS selectOneByExample(TbDBSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    TbDBS selectOneByExampleSelective(@Param("example") TbDBSExample example, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    List<TbDBS> selectByExampleSelective(@Param("example") TbDBSExample example, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    List<TbDBS> selectByExample(TbDBSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    TbDBS selectByPrimaryKeySelective(@Param("dbId") Long dbId, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    TbDBS selectByPrimaryKey(Long dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbDBS record, @Param("example") TbDBSExample example, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbDBS record, @Param("example") TbDBSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TbDBS record, @Param("selective") TbDBS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DBS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbDBS record);
}