package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.TbPartitions;
import com.qmtec.servicecore.entity.example.TbPartitionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPartitionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    long countByExample(TbPartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int deleteByExample(TbPartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int insert(TbPartitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TbPartitions record, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    TbPartitions selectOneByExample(TbPartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    TbPartitions selectOneByExampleSelective(@Param("example") TbPartitionsExample example, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    List<TbPartitions> selectByExampleSelective(@Param("example") TbPartitionsExample example, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    List<TbPartitions> selectByExample(TbPartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    TbPartitions selectByPrimaryKeySelective(@Param("partId") Long partId, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    TbPartitions selectByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbPartitions record, @Param("example") TbPartitionsExample example, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbPartitions record, @Param("example") TbPartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TbPartitions record, @Param("selective") TbPartitions.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITIONS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPartitions record);
}