package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.TbPartitionKeys;
import com.qmtec.servicecore.entity.example.TbPartitionKeysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPartitionKeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    long countByExample(TbPartitionKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int deleteByExample(TbPartitionKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("tblId") Long tblId, @Param("pkeyName") String pkeyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int insert(TbPartitionKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TbPartitionKeys record, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    TbPartitionKeys selectOneByExample(TbPartitionKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    TbPartitionKeys selectOneByExampleSelective(@Param("example") TbPartitionKeysExample example, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    List<TbPartitionKeys> selectByExampleSelective(@Param("example") TbPartitionKeysExample example, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    List<TbPartitionKeys> selectByExample(TbPartitionKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    TbPartitionKeys selectByPrimaryKeySelective(@Param("tblId") Long tblId, @Param("pkeyName") String pkeyName, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    TbPartitionKeys selectByPrimaryKey(@Param("tblId") Long tblId, @Param("pkeyName") String pkeyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbPartitionKeys record, @Param("example") TbPartitionKeysExample example, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbPartitionKeys record, @Param("example") TbPartitionKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TbPartitionKeys record, @Param("selective") TbPartitionKeys.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEYS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPartitionKeys record);
}