package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.TbPartitionKeyVal;
import com.qmtec.servicecore.entity.example.TbPartitionKeyValExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPartitionKeyValMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    long countByExample(TbPartitionKeyValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int deleteByExample(TbPartitionKeyValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("partId") Long partId, @Param("integerIdx") Integer integerIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int insert(TbPartitionKeyVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TbPartitionKeyVal record, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    TbPartitionKeyVal selectOneByExample(TbPartitionKeyValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    TbPartitionKeyVal selectOneByExampleSelective(@Param("example") TbPartitionKeyValExample example, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    List<TbPartitionKeyVal> selectByExampleSelective(@Param("example") TbPartitionKeyValExample example, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    List<TbPartitionKeyVal> selectByExample(TbPartitionKeyValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    TbPartitionKeyVal selectByPrimaryKeySelective(@Param("partId") Long partId, @Param("integerIdx") Integer integerIdx, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    TbPartitionKeyVal selectByPrimaryKey(@Param("partId") Long partId, @Param("integerIdx") Integer integerIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbPartitionKeyVal record, @Param("example") TbPartitionKeyValExample example, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbPartitionKeyVal record, @Param("example") TbPartitionKeyValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TbPartitionKeyVal record, @Param("selective") TbPartitionKeyVal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTITION_KEY_VALS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPartitionKeyVal record);
}