package com.qmtec.servicecore.dao;

import com.qmtec.servicecore.entity.TbTBLS;
import com.qmtec.servicecore.entity.example.TbTBLSExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTBLSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    long countByExample(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int deleteByExample(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tblId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int insert(TbTBLS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") TbTBLS record, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    TbTBLS selectOneByExample(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    TbTBLS selectOneByExampleSelective(@Param("example") TbTBLSExample example, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    TbTBLS selectOneByExampleWithBLOBs(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    List<TbTBLS> selectByExampleSelective(@Param("example") TbTBLSExample example, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    List<TbTBLS> selectByExampleWithBLOBs(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    List<TbTBLS> selectByExample(TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    TbTBLS selectByPrimaryKeySelective(@Param("tblId") Long tblId, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    TbTBLS selectByPrimaryKey(Long tblId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTBLS record, @Param("example") TbTBLSExample example, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbTBLS record, @Param("example") TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTBLS record, @Param("example") TbTBLSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") TbTBLS record, @Param("selective") TbTBLS.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbTBLS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBLS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTBLS record);
}